version: "3"
services:
  web:
    build: .
    image: crichmond1989/pingpongpeer:latest
    container_name: pingpongpeer
    command: "npm start -- -S -C cert.pem -K key.pem"
    ports:
    - "443:8080"
    restart: "unless-stopped"
